/////////////////// createMatrix ///////////////////

// Now its hardcoded
export const matrix = [
  {
    x: 0,
    y: 0,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 0,
    y: 1,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 0,
    y: 2,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 0,
    y: 3,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 1,
    y: 0,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 1,
    y: 1,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 1,
    y: 2,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 1,
    y: 3,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 2,
    y: 0,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 2,
    y: 1,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 2,
    y: 2,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 2,
    y: 3,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 3,
    y: 0,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 3,
    y: 1,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 3,
    y: 2,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
  {
    x: 3,
    y: 3,
    isAlive: true,
    position: {
      firstRow: false,
      firstCol: false,
      lastRow: false,
      lastCol: false,
    },
    neighbours: [],
  },
];
